/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Admin: () => import('#controllers/admin_controller'),
  AdminQuotes: () => import('#controllers/admin_quotes_controller'),
  AdminRequests: () => import('#controllers/admin_requests_controller'),
  AdminSpaces: () => import('#controllers/admin_spaces_controller'),
  auth: {
    AdminAuth: () => import('#controllers/auth/admin_auth_controller'),
    CompanyAuth: () => import('#controllers/auth/company_auth_controller'),
    UserAuth: () => import('#controllers/auth/user_auth_controller'),
  },
  CompanyBooking: () => import('#controllers/company_booking_controller'),
  CompanyCalendar: () => import('#controllers/company_calendar_controller'),
  CompanyInvitations: () => import('#controllers/company_invitations_controller'),
  CompanyMembers: () => import('#controllers/company_members_controller'),
  CompanyPricing: () => import('#controllers/company_pricing_controller'),
  CompanyQuotes: () => import('#controllers/company_quotes_controller'),
  CompanyRequests: () => import('#controllers/company_requests_controller'),
  Hall: () => import('#controllers/hall_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  Notification: () => import('#controllers/notification_controller'),
  PublicAvailability: () => import('#controllers/public_availability_controller'),
  PublicCompanyInvitations: () => import('#controllers/public_company_invitations_controller'),
  PublicHall: () => import('#controllers/public_hall_controller'),
  PublicPricing: () => import('#controllers/public_pricing_controller'),
  PublicSpaces: () => import('#controllers/public_spaces_controller'),
  PushInstallations: () => import('#controllers/push_installations_controller'),
  SpaceCatalog: () => import('#controllers/space_catalog_controller'),
  Spaces: () => import('#controllers/spaces_controller'),
  UserBooking: () => import('#controllers/user_booking_controller'),
  UserPushInstallations: () => import('#controllers/user_push_installations_controller'),
  UserQuotes: () => import('#controllers/user_quotes_controller'),
  UserRequests: () => import('#controllers/user_requests_controller'),
  Venues: () => import('#controllers/venues_controller'),
}
