/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Admin: () => import('#controllers/admin_controller'),
  auth: {
    AdminAuth: () => import('#controllers/auth/admin_auth_controller'),
    CompanyAuth: () => import('#controllers/auth/company_auth_controller'),
    UserAuth: () => import('#controllers/auth/user_auth_controller'),
  },
  CompanyBooking: () => import('#controllers/company_booking_controller'),
  Hall: () => import('#controllers/hall_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  Notification: () => import('#controllers/notification_controller'),
  PublicHall: () => import('#controllers/public_hall_controller'),
  PushInstallations: () => import('#controllers/push_installations_controller'),
  UserBooking: () => import('#controllers/user_booking_controller'),
  UserPushInstallations: () => import('#controllers/user_push_installations_controller'),
}
