/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class BookingServiceSchema extends BaseModel {
  static $columns = ['id', 'bookingId', 'serviceId', 'priceAtBooking', 'createdAt', 'updatedAt'] as const
  $columns = BookingServiceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare bookingId: number
  @column()
  declare serviceId: number
  @column()
  declare priceAtBooking: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BookingSchema extends BaseModel {
  static $columns = ['id', 'bookingDate', 'startTime', 'endTime', 'status', 'totalPrice', 'specialRequests', 'userId', 'hallId', 'createdAt', 'updatedAt', 'deletedAt', 'rejectionReason', 'companyRespondedAt', 'expiresAt', 'paymentStatus', 'paymentDueDate'] as const
  $columns = BookingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare bookingDate: DateTime
  @column()
  declare startTime: string
  @column()
  declare endTime: string
  @column()
  declare status: string
  @column()
  declare totalPrice: string
  @column()
  declare specialRequests: string | null
  @column()
  declare userId: number
  @column()
  declare hallId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare rejectionReason: string | null
  @column.dateTime()
  declare companyRespondedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare paymentStatus: string
  @column.dateTime()
  declare paymentDueDate: DateTime | null
}

export class CompanySchema extends BaseModel {
  static $columns = ['id', 'taxId', 'registrationNumber', 'registrationNumberPdf', 'businessLicense', 'contactPerson', 'businessAddress', 'city', 'userId', 'createdAt', 'updatedAt', 'deletedAt', 'status', 'approvedAt', 'approvedBy', 'rejectionReason', 'rejectedAt'] as const
  $columns = CompanySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare taxId: string | null
  @column()
  declare registrationNumber: string | null
  @column()
  declare registrationNumberPdf: string | null
  @column()
  declare businessLicense: string | null
  @column()
  declare contactPerson: string | null
  @column()
  declare businessAddress: string | null
  @column()
  declare city: string
  @column()
  declare userId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare approvedBy: number | null
  @column()
  declare rejectionReason: string | null
  @column.dateTime()
  declare rejectedAt: DateTime | null
}

export class CompanyProfileSchema extends BaseModel {
  static $columns = ['id', 'companyName', 'description', 'logo', 'banner', 'website', 'socialLinks', 'userId', 'createdAt', 'updatedAt', 'deletedAt'] as const
  $columns = CompanyProfileSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare companyName: string
  @column()
  declare description: string | null
  @column()
  declare logo: string | null
  @column()
  declare banner: string | null
  @column()
  declare website: string | null
  @column()
  declare socialLinks: any | null
  @column()
  declare userId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
}

export class HallSchema extends BaseModel {
  static $columns = ['id', 'name', 'description', 'capacity', 'location', 'amenities', 'pricing', 'images', 'address', 'city', 'isAvailable', 'companyId', 'createdAt', 'updatedAt', 'deletedAt', 'services'] as const
  $columns = HallSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare capacity: number
  @column()
  declare location: string
  @column()
  declare amenities: any | null
  @column()
  declare pricing: string
  @column()
  declare images: any | null
  @column()
  declare address: string
  @column()
  declare city: string
  @column()
  declare isAvailable: boolean
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare services: any | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['id', 'userId', 'type', 'title', 'message', 'data', 'readAt', 'createdAt'] as const
  $columns = NotificationSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare userId: number
  @column()
  declare type: string
  @column()
  declare title: string
  @column()
  declare message: string
  @column()
  declare data: any | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class ServiceSchema extends BaseModel {
  static $columns = ['id', 'name', 'description', 'price', 'isActive', 'companyId', 'createdAt', 'updatedAt', 'deletedAt'] as const
  $columns = ServiceSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare price: string
  @column()
  declare isActive: boolean
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
}

export class UserProfileSchema extends BaseModel {
  static $columns = ['id', 'firstName', 'lastName', 'phone', 'address', 'avatar', 'userId', 'createdAt', 'updatedAt', 'deletedAt'] as const
  $columns = UserProfileSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare firstName: string | null
  @column()
  declare lastName: string | null
  @column()
  declare phone: string | null
  @column()
  declare address: string | null
  @column()
  declare avatar: string | null
  @column()
  declare userId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'userName', 'email', 'password', 'createdAt', 'updatedAt', 'deletedAt', 'userType', 'emailVerifiedAt', 'emailVerificationToken', 'emailVerificationExpiresAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userName: string
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare userType: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare emailVerificationToken: string | null
  @column.dateTime()
  declare emailVerificationExpiresAt: DateTime | null
}
