/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminAuditLogSchema extends BaseModel {
  static $columns = ['action', 'adminUserId', 'createdAt', 'id', 'metadata', 'reason', 'targetId', 'targetType'] as const
  $columns = AdminAuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare adminUserId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare reason: string | null
  @column()
  declare targetId: number
  @column()
  declare targetType: string
}

export class AmenityDefinitionSchema extends BaseModel {
  static $columns = ['createdAt', 'group', 'id', 'isActive', 'isSearchable', 'nameAr', 'nameEn', 'slug', 'updatedAt'] as const
  $columns = AmenityDefinitionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare group: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isSearchable: boolean
  @column()
  declare nameAr: string
  @column()
  declare nameEn: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AvailabilityExceptionSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'createdByUserId', 'endsAtLocal', 'endsNextDay', 'id', 'kind', 'localDate', 'reason', 'spaceId', 'startsAtLocal', 'updatedAt'] as const
  $columns = AvailabilityExceptionSchema.$columns
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare endsAtLocal: string | null
  @column()
  declare endsNextDay: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column.date()
  declare localDate: DateTime
  @column()
  declare reason: string | null
  @column()
  declare spaceId: number
  @column()
  declare startsAtLocal: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BookingAuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorUserId', 'bookingId', 'companyId', 'createdAt', 'id', 'metadata', 'nextStatus', 'previousStatus', 'reason'] as const
  $columns = BookingAuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: number | null
  @column()
  declare bookingId: number
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare nextStatus: string
  @column()
  declare previousStatus: string
  @column()
  declare reason: string | null
}

export class BookingHoldSchema extends BaseModel {
  static $columns = ['bookingId', 'companyId', 'createdAt', 'endsAt', 'expiresAt', 'id', 'purpose', 'releaseReason', 'releasedAt', 'spaceId', 'startsAt', 'status', 'updatedAt'] as const
  $columns = BookingHoldSchema.$columns
  @column()
  declare bookingId: number
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endsAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare purpose: string
  @column()
  declare releaseReason: string | null
  @column.dateTime()
  declare releasedAt: DateTime | null
  @column()
  declare spaceId: number
  @column.dateTime()
  declare startsAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BookingInventoryMigrationReportSchema extends BaseModel {
  static $columns = ['acceptedElapsedDeadline', 'acceptedFutureDeadline', 'acceptedMissingDeadline', 'createdAt', 'id', 'statusCounts'] as const
  $columns = BookingInventoryMigrationReportSchema.$columns
  @column()
  declare acceptedElapsedDeadline: number
  @column()
  declare acceptedFutureDeadline: number
  @column()
  declare acceptedMissingDeadline: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare statusCounts: any
}

export class BookingServiceSchema extends BaseModel {
  static $columns = ['bookingId', 'createdAt', 'id', 'priceAtBooking', 'serviceId', 'updatedAt'] as const
  $columns = BookingServiceSchema.$columns
  @column()
  declare bookingId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare priceAtBooking: string
  @column()
  declare serviceId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BookingSchema extends BaseModel {
  static $columns = ['attendance', 'bookingDate', 'categoryRequirements', 'categorySlugSnapshot', 'companyId', 'companyRespondedAt', 'contactPreference', 'createdAt', 'customerEmailSnapshot', 'customerNameSnapshot', 'customerPhoneSnapshot', 'deletedAt', 'endTime', 'endsAt', 'eventType', 'expiresAt', 'hallId', 'id', 'lockVersion', 'originalEndLocal', 'originalStartLocal', 'originalTimezone', 'paymentDueDate', 'paymentStatus', 'rejectionReason', 'requestReference', 'requestSource', 'requirementsSchemaVersion', 'responseExpiresAt', 'sessionCode', 'spaceId', 'spaceNameSnapshotAr', 'spaceNameSnapshotEn', 'specialRequests', 'startTime', 'startsAt', 'status', 'submittedAt', 'totalPrice', 'updatedAt', 'userId', 'venueId', 'venueNameSnapshotAr', 'venueNameSnapshotEn'] as const
  $columns = BookingSchema.$columns
  @column()
  declare attendance: number | null
  @column.date()
  declare bookingDate: DateTime
  @column()
  declare categoryRequirements: any | null
  @column()
  declare categorySlugSnapshot: string | null
  @column()
  declare companyId: number | null
  @column.dateTime()
  declare companyRespondedAt: DateTime | null
  @column()
  declare contactPreference: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerEmailSnapshot: string | null
  @column()
  declare customerNameSnapshot: string | null
  @column()
  declare customerPhoneSnapshot: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare endTime: string
  @column.dateTime()
  declare endsAt: DateTime | null
  @column()
  declare eventType: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hallId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lockVersion: number
  @column()
  declare originalEndLocal: string | null
  @column()
  declare originalStartLocal: string | null
  @column()
  declare originalTimezone: string | null
  @column.dateTime()
  declare paymentDueDate: DateTime | null
  @column()
  declare paymentStatus: string
  @column()
  declare rejectionReason: string | null
  @column()
  declare requestReference: string | null
  @column()
  declare requestSource: string
  @column()
  declare requirementsSchemaVersion: number
  @column.dateTime()
  declare responseExpiresAt: DateTime | null
  @column()
  declare sessionCode: string | null
  @column()
  declare spaceId: number | null
  @column()
  declare spaceNameSnapshotAr: string | null
  @column()
  declare spaceNameSnapshotEn: string | null
  @column()
  declare specialRequests: string | null
  @column()
  declare startTime: string
  @column.dateTime()
  declare startsAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime()
  declare submittedAt: DateTime | null
  @column()
  declare totalPrice: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare venueId: number | null
  @column()
  declare venueNameSnapshotAr: string | null
  @column()
  declare venueNameSnapshotEn: string | null
}

export class CategoryRequestResponsePolicySchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'dateInquiryHours', 'id', 'requestToBookHours', 'updatedAt', 'visitHours'] as const
  $columns = CategoryRequestResponsePolicySchema.$columns
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dateInquiryHours: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare requestToBookHours: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visitHours: number
}

export class CompanySchema extends BaseModel {
  static $columns = ['approvedAt', 'approvedBy', 'businessAddress', 'businessLicense', 'city', 'contactPerson', 'createdAt', 'deletedAt', 'id', 'registrationNumber', 'registrationNumberPdf', 'rejectedAt', 'rejectionReason', 'status', 'taxId', 'updatedAt', 'userId'] as const
  $columns = CompanySchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare approvedBy: number | null
  @column()
  declare businessAddress: string | null
  @column()
  declare businessLicense: string | null
  @column()
  declare city: string
  @column()
  declare contactPerson: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare registrationNumber: string | null
  @column()
  declare registrationNumberPdf: string | null
  @column.dateTime()
  declare rejectedAt: DateTime | null
  @column()
  declare rejectionReason: string | null
  @column()
  declare status: string
  @column()
  declare taxId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class CompanyAuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorUserId', 'companyId', 'createdAt', 'id', 'metadata', 'targetId', 'targetType'] as const
  $columns = CompanyAuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: number | null
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare metadata: any | null
  @column()
  declare targetId: number
  @column()
  declare targetType: string
}

export class CompanyInvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'acceptedByUserId', 'cancelledAt', 'companyId', 'createdAt', 'expiresAt', 'id', 'invitedByUserId', 'invitedEmail', 'invitedPhone', 'name', 'permissionOverrides', 'role', 'status', 'tokenHash', 'updatedAt'] as const
  $columns = CompanyInvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column()
  declare acceptedByUserId: number | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedByUserId: number
  @column()
  declare invitedEmail: string | null
  @column()
  declare invitedPhone: string | null
  @column()
  declare name: string
  @column()
  declare permissionOverrides: any | null
  @column()
  declare role: string
  @column()
  declare status: string
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CompanyMembershipPermissionSchema extends BaseModel {
  static $columns = ['companyMembershipId', 'createdAt', 'effect', 'id', 'permission', 'updatedAt'] as const
  $columns = CompanyMembershipPermissionSchema.$columns
  @column()
  declare companyMembershipId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare effect: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare permission: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CompanyMembershipSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'id', 'invitedByUserId', 'joinedAt', 'role', 'status', 'updatedAt', 'userId'] as const
  $columns = CompanyMembershipSchema.$columns
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedByUserId: number | null
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class CompanyProfileSchema extends BaseModel {
  static $columns = ['banner', 'companyName', 'createdAt', 'deletedAt', 'description', 'id', 'logo', 'socialLinks', 'updatedAt', 'userId', 'website'] as const
  $columns = CompanyProfileSchema.$columns
  @column()
  declare banner: string | null
  @column()
  declare companyName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare logo: string | null
  @column()
  declare socialLinks: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare website: string | null
}

export class ExternalReservationSchema extends BaseModel {
  static $columns = ['cancelledAt', 'cleanupBufferMinutes', 'companyId', 'createdAt', 'createdByUserId', 'endsAt', 'expiresAt', 'id', 'internalNote', 'originalEndLocal', 'originalStartLocal', 'originalTimezone', 'preparationBufferMinutes', 'spaceId', 'startsAt', 'status', 'type', 'updatedAt'] as const
  $columns = ExternalReservationSchema.$columns
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cleanupBufferMinutes: number
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column.dateTime()
  declare endsAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare internalNote: string | null
  @column()
  declare originalEndLocal: string
  @column()
  declare originalStartLocal: string
  @column()
  declare originalTimezone: string
  @column()
  declare preparationBufferMinutes: number
  @column()
  declare spaceId: number
  @column.dateTime()
  declare startsAt: DateTime
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class HallSchema extends BaseModel {
  static $columns = ['address', 'amenities', 'capacity', 'city', 'companyId', 'createdAt', 'deletedAt', 'description', 'id', 'images', 'isAvailable', 'location', 'name', 'pricing', 'services', 'updatedAt'] as const
  $columns = HallSchema.$columns
  @column()
  declare address: string
  @column()
  declare amenities: any | null
  @column()
  declare capacity: number
  @column()
  declare city: string
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare images: any | null
  @column()
  declare isAvailable: boolean
  @column()
  declare location: string
  @column()
  declare name: string
  @column()
  declare pricing: string
  @column()
  declare services: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InquiryEventSchema extends BaseModel {
  static $columns = ['action', 'actorUserId', 'companyId', 'createdAt', 'id', 'inquiryId', 'metadata', 'nextStatus', 'previousStatus', 'reason'] as const
  $columns = InquiryEventSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: number | null
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare inquiryId: number
  @column()
  declare metadata: any | null
  @column()
  declare nextStatus: string
  @column()
  declare previousStatus: string | null
  @column()
  declare reason: string | null
}

export class InquiryMessageSchema extends BaseModel {
  static $columns = ['body', 'companyId', 'createdAt', 'id', 'inquiryId', 'senderType', 'senderUserId'] as const
  $columns = InquiryMessageSchema.$columns
  @column()
  declare body: string
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare inquiryId: number
  @column()
  declare senderType: string
  @column()
  declare senderUserId: number
}

export class NotificationOutboxSchema extends BaseModel {
  static $columns = ['attempts', 'availableAt', 'createdAt', 'id', 'lastError', 'payload', 'processedAt', 'processingStartedAt'] as const
  $columns = NotificationOutboxSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime()
  declare availableAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare lastError: string | null
  @column()
  declare payload: any
  @column.dateTime()
  declare processedAt: DateTime | null
  @column.dateTime()
  declare processingStartedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'id', 'message', 'outboxId', 'readAt', 'title', 'type', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: any | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare message: string
  @column()
  declare outboxId: bigint | number | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare title: string
  @column()
  declare type: string
  @column()
  declare userId: number
}

export class PushDeliverySchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'expoTicketId', 'id', 'lastErrorCode', 'lastErrorMessage', 'nextAttemptAt', 'notificationId', 'processingStartedAt', 'providerAcceptedAt', 'pushInstallationId', 'receiptCheckedAt', 'sentAt', 'status', 'updatedAt'] as const
  $columns = PushDeliverySchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expoTicketId: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare lastErrorCode: string | null
  @column()
  declare lastErrorMessage: string | null
  @column.dateTime()
  declare nextAttemptAt: DateTime | null
  @column()
  declare notificationId: bigint | number
  @column.dateTime()
  declare processingStartedAt: DateTime | null
  @column.dateTime()
  declare providerAcceptedAt: DateTime | null
  @column()
  declare pushInstallationId: bigint | number
  @column.dateTime()
  declare receiptCheckedAt: DateTime | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PushInstallationSchema extends BaseModel {
  static $columns = ['appVersion', 'clientContext', 'createdAt', 'deviceName', 'expoPushToken', 'id', 'installationId', 'lastSeenAt', 'notificationsEnabled', 'platform', 'revokedAt', 'updatedAt', 'userId'] as const
  $columns = PushInstallationSchema.$columns
  @column()
  declare appVersion: string | null
  @column()
  declare clientContext: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceName: string | null
  @column()
  declare expoPushToken: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare installationId: string
  @column.dateTime()
  declare lastSeenAt: DateTime
  @column()
  declare notificationsEnabled: boolean
  @column()
  declare platform: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RequestIdempotencyKeySchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'idempotencyKey', 'requestHash', 'resourceId', 'resourceType', 'scope', 'userId'] as const
  $columns = RequestIdempotencyKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare idempotencyKey: string
  @column()
  declare requestHash: string
  @column()
  declare resourceId: number
  @column()
  declare resourceType: string
  @column()
  declare scope: string
  @column()
  declare userId: number
}

export class ServiceSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'deletedAt', 'description', 'id', 'isActive', 'name', 'price', 'updatedAt'] as const
  $columns = ServiceSchema.$columns
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare price: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SpaceAmenitySchema extends BaseModel {
  static $columns = ['amenityDefinitionId', 'createdAt', 'id', 'spaceId'] as const
  $columns = SpaceAmenitySchema.$columns
  @column()
  declare amenityDefinitionId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare spaceId: number
}

export class SpaceAvailabilityPolicySchema extends BaseModel {
  static $columns = ['cleanupBufferMinutes', 'companyId', 'createdAt', 'id', 'isActive', 'maximumAdvanceDays', 'maximumDurationMinutes', 'minimumDurationMinutes', 'minimumNoticeMinutes', 'mode', 'preparationBufferMinutes', 'slotIncrementMinutes', 'source', 'spaceId', 'updatedAt'] as const
  $columns = SpaceAvailabilityPolicySchema.$columns
  @column()
  declare cleanupBufferMinutes: number
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare maximumAdvanceDays: number
  @column()
  declare maximumDurationMinutes: number
  @column()
  declare minimumDurationMinutes: number
  @column()
  declare minimumNoticeMinutes: number
  @column()
  declare mode: string
  @column()
  declare preparationBufferMinutes: number
  @column()
  declare slotIncrementMinutes: number
  @column()
  declare source: string
  @column()
  declare spaceId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SpaceAvailabilitySessionSchema extends BaseModel {
  static $columns = ['code', 'companyId', 'createdAt', 'endsAtLocal', 'endsNextDay', 'id', 'isActive', 'nameAr', 'nameEn', 'spaceId', 'startsAtLocal', 'updatedAt', 'weekday'] as const
  $columns = SpaceAvailabilitySessionSchema.$columns
  @column()
  declare code: string
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endsAtLocal: string
  @column()
  declare endsNextDay: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare nameAr: string | null
  @column()
  declare nameEn: string | null
  @column()
  declare spaceId: number
  @column()
  declare startsAtLocal: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weekday: number
}

export class SpaceCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'nameAr', 'nameEn', 'slug', 'sortOrder', 'updatedAt'] as const
  $columns = SpaceCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare nameAr: string
  @column()
  declare nameEn: string
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SpaceEventDetailSchema extends BaseModel {
  static $columns = ['createdAt', 'femaleCapacity', 'hasBridalRoom', 'hasSeparateEntrances', 'hasStage', 'maleCapacity', 'spaceId', 'updatedAt'] as const
  $columns = SpaceEventDetailSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare femaleCapacity: number | null
  @column()
  declare hasBridalRoom: boolean | null
  @column()
  declare hasSeparateEntrances: boolean | null
  @column()
  declare hasStage: boolean | null
  @column()
  declare maleCapacity: number | null
  @column({ isPrimary: true })
  declare spaceId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SpaceInquirySchema extends BaseModel {
  static $columns = ['answeredAt', 'attendance', 'cancelledAt', 'closedAt', 'companyId', 'contactPreference', 'createdAt', 'customerEmailSnapshot', 'customerNameSnapshot', 'deletedAt', 'eventType', 'id', 'initialMessage', 'kind', 'lockVersion', 'originalEndLocal', 'originalStartLocal', 'originalTimezone', 'preferredEndsAt', 'preferredStartsAt', 'reference', 'responseExpiresAt', 'spaceId', 'spaceNameSnapshotAr', 'spaceNameSnapshotEn', 'status', 'subject', 'updatedAt', 'userId', 'venueId', 'venueNameSnapshotAr', 'venueNameSnapshotEn'] as const
  $columns = SpaceInquirySchema.$columns
  @column.dateTime()
  declare answeredAt: DateTime | null
  @column()
  declare attendance: number | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column.dateTime()
  declare closedAt: DateTime | null
  @column()
  declare companyId: number
  @column()
  declare contactPreference: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerEmailSnapshot: string | null
  @column()
  declare customerNameSnapshot: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare eventType: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare initialMessage: string | null
  @column()
  declare kind: string
  @column()
  declare lockVersion: number
  @column()
  declare originalEndLocal: string
  @column()
  declare originalStartLocal: string
  @column()
  declare originalTimezone: string
  @column.dateTime()
  declare preferredEndsAt: DateTime
  @column.dateTime()
  declare preferredStartsAt: DateTime
  @column()
  declare reference: string
  @column.dateTime()
  declare responseExpiresAt: DateTime
  @column()
  declare spaceId: number
  @column()
  declare spaceNameSnapshotAr: string | null
  @column()
  declare spaceNameSnapshotEn: string | null
  @column()
  declare status: string
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare venueId: number
  @column()
  declare venueNameSnapshotAr: string | null
  @column()
  declare venueNameSnapshotEn: string | null
}

export class SpaceInventoryBlockSchema extends BaseModel {
  static $columns = ['blockedFromAt', 'blockedUntilAt', 'bookingHoldId', 'bookingId', 'companyId', 'createdAt', 'endsAt', 'externalReservationId', 'id', 'releaseReason', 'releasedAt', 'spaceId', 'startsAt', 'status', 'updatedAt'] as const
  $columns = SpaceInventoryBlockSchema.$columns
  @column.dateTime()
  declare blockedFromAt: DateTime
  @column.dateTime()
  declare blockedUntilAt: DateTime
  @column()
  declare bookingHoldId: number | null
  @column()
  declare bookingId: number | null
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endsAt: DateTime
  @column()
  declare externalReservationId: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare releaseReason: string | null
  @column.dateTime()
  declare releasedAt: DateTime | null
  @column()
  declare spaceId: number
  @column.dateTime()
  declare startsAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SpaceInventoryEventSchema extends BaseModel {
  static $columns = ['action', 'actorUserId', 'companyId', 'createdAt', 'id', 'inventoryBlockId', 'metadata', 'spaceId'] as const
  $columns = SpaceInventoryEventSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: number | null
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare inventoryBlockId: bigint | number | null
  @column()
  declare metadata: any | null
  @column()
  declare spaceId: number
}

export class SpaceLargeFormatDetailSchema extends BaseModel {
  static $columns = ['ceilingHeightM', 'createdAt', 'floorAreaSqm', 'hasLoadingAccess', 'powerRequirement', 'spaceId', 'updatedAt', 'visitorCapacity'] as const
  $columns = SpaceLargeFormatDetailSchema.$columns
  @column()
  declare ceilingHeightM: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare floorAreaSqm: string | null
  @column()
  declare hasLoadingAccess: boolean | null
  @column()
  declare powerRequirement: string | null
  @column({ isPrimary: true })
  declare spaceId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visitorCapacity: number | null
}

export class SpaceLayoutCapacitySchema extends BaseModel {
  static $columns = ['capacity', 'createdAt', 'id', 'layout', 'spaceId', 'updatedAt'] as const
  $columns = SpaceLayoutCapacitySchema.$columns
  @column()
  declare capacity: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare layout: string
  @column()
  declare spaceId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SpaceMediaSchema extends BaseModel {
  static $columns = ['altTextAr', 'altTextEn', 'createdAt', 'id', 'isCover', 'legacyReference', 'mediaType', 'moderationStatus', 'provenance', 'sortOrder', 'spaceId', 'storageKey', 'updatedAt'] as const
  $columns = SpaceMediaSchema.$columns
  @column()
  declare altTextAr: string | null
  @column()
  declare altTextEn: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCover: boolean
  @column()
  declare legacyReference: string | null
  @column()
  declare mediaType: string
  @column()
  declare moderationStatus: string
  @column()
  declare provenance: string
  @column()
  declare sortOrder: number
  @column()
  declare spaceId: number
  @column()
  declare storageKey: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SpaceModerationEventSchema extends BaseModel {
  static $columns = ['action', 'actorUserId', 'companyId', 'createdAt', 'id', 'metadata', 'nextStatus', 'previousStatus', 'reason', 'spaceId'] as const
  $columns = SpaceModerationEventSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: number | null
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare metadata: any | null
  @column()
  declare nextStatus: string
  @column()
  declare previousStatus: string | null
  @column()
  declare reason: string | null
  @column()
  declare spaceId: number
}

export class SpaceOperatingHourSchema extends BaseModel {
  static $columns = ['closesAtLocal', 'companyId', 'createdAt', 'endsNextDay', 'id', 'opensAtLocal', 'sortOrder', 'spaceId', 'weekday'] as const
  $columns = SpaceOperatingHourSchema.$columns
  @column()
  declare closesAtLocal: string
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endsNextDay: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare opensAtLocal: string
  @column()
  declare sortOrder: number
  @column()
  declare spaceId: number
  @column()
  declare weekday: number
}

export class SpaceRequestSettingSchema extends BaseModel {
  static $columns = ['bookingResponseHours', 'companyId', 'createdAt', 'id', 'inquiryResponseHours', 'spaceId', 'updatedAt', 'visitResponseHours'] as const
  $columns = SpaceRequestSettingSchema.$columns
  @column()
  declare bookingResponseHours: number | null
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inquiryResponseHours: number | null
  @column()
  declare spaceId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visitResponseHours: number | null
}

export class SpaceSchema extends BaseModel {
  static $columns = ['bookingMode', 'capacityTotal', 'categoryId', 'companyId', 'createdAt', 'deletedAt', 'descriptionAr', 'descriptionEn', 'id', 'instantBookApprovedAt', 'instantBookApprovedBy', 'legacyDescription', 'legacyHallId', 'legacyIsAvailable', 'legacyName', 'maximumDurationMinutes', 'minimumDurationMinutes', 'minimumNoticeHours', 'nameAr', 'nameEn', 'publicationStatus', 'publishedAt', 'publishedBy', 'requiresVisit', 'updatedAt', 'venueId'] as const
  $columns = SpaceSchema.$columns
  @column()
  declare bookingMode: string
  @column()
  declare capacityTotal: number
  @column()
  declare categoryId: number
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descriptionAr: string | null
  @column()
  declare descriptionEn: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare instantBookApprovedAt: DateTime | null
  @column()
  declare instantBookApprovedBy: number | null
  @column()
  declare legacyDescription: string | null
  @column()
  declare legacyHallId: number | null
  @column()
  declare legacyIsAvailable: boolean | null
  @column()
  declare legacyName: string | null
  @column()
  declare maximumDurationMinutes: number | null
  @column()
  declare minimumDurationMinutes: number | null
  @column()
  declare minimumNoticeHours: number | null
  @column()
  declare nameAr: string | null
  @column()
  declare nameEn: string | null
  @column()
  declare publicationStatus: string
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare publishedBy: number | null
  @column()
  declare requiresVisit: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare venueId: number
}

export class UserProfileSchema extends BaseModel {
  static $columns = ['address', 'avatar', 'createdAt', 'deletedAt', 'firstName', 'id', 'lastName', 'phone', 'updatedAt', 'userId'] as const
  $columns = UserProfileSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'emailVerificationExpiresAt', 'emailVerificationToken', 'emailVerifiedAt', 'id', 'password', 'updatedAt', 'userName', 'userType'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerificationExpiresAt: DateTime | null
  @column()
  declare emailVerificationToken: string | null
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userName: string
  @column()
  declare userType: string
}

export class VenueSchema extends BaseModel {
  static $columns = ['accessInstructionsAr', 'accessInstructionsEn', 'additionalNumber', 'buildingNumber', 'city', 'companyId', 'createdAt', 'deletedAt', 'district', 'id', 'latitude', 'legacyAddress', 'legacyLocation', 'legacyName', 'longitude', 'nameAr', 'nameEn', 'parkingNotesAr', 'parkingNotesEn', 'postalCode', 'street', 'timezone', 'updatedAt', 'verificationStatus'] as const
  $columns = VenueSchema.$columns
  @column()
  declare accessInstructionsAr: string | null
  @column()
  declare accessInstructionsEn: string | null
  @column()
  declare additionalNumber: string | null
  @column()
  declare buildingNumber: string | null
  @column()
  declare city: string
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare district: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: string | null
  @column()
  declare legacyAddress: string | null
  @column()
  declare legacyLocation: string | null
  @column()
  declare legacyName: string | null
  @column()
  declare longitude: string | null
  @column()
  declare nameAr: string | null
  @column()
  declare nameEn: string | null
  @column()
  declare parkingNotesAr: string | null
  @column()
  declare parkingNotesEn: string | null
  @column()
  declare postalCode: string | null
  @column()
  declare street: string | null
  @column()
  declare timezone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare verificationStatus: string
}

export class VisitEventSchema extends BaseModel {
  static $columns = ['action', 'actorUserId', 'companyId', 'createdAt', 'id', 'metadata', 'nextStatus', 'previousStatus', 'reason', 'visitId'] as const
  $columns = VisitEventSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: number | null
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare metadata: any | null
  @column()
  declare nextStatus: string
  @column()
  declare previousStatus: string | null
  @column()
  declare reason: string | null
  @column()
  declare visitId: number
}

export class VisitRequestSchema extends BaseModel {
  static $columns = ['bookingId', 'cancelledAt', 'companyId', 'completedAt', 'confirmedAt', 'createdAt', 'customerEmailSnapshot', 'customerNameSnapshot', 'customerNotes', 'deletedAt', 'endsAt', 'id', 'inquiryId', 'lockVersion', 'originalEndLocal', 'originalStartLocal', 'originalTimezone', 'proposedEndLocal', 'proposedEndsAt', 'proposedStartLocal', 'proposedStartsAt', 'providerNotes', 'reference', 'responseExpiresAt', 'spaceId', 'startsAt', 'status', 'statusReason', 'updatedAt', 'userId', 'venueId'] as const
  $columns = VisitRequestSchema.$columns
  @column()
  declare bookingId: number | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare companyId: number
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerEmailSnapshot: string | null
  @column()
  declare customerNameSnapshot: string | null
  @column()
  declare customerNotes: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime()
  declare endsAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inquiryId: number | null
  @column()
  declare lockVersion: number
  @column()
  declare originalEndLocal: string
  @column()
  declare originalStartLocal: string
  @column()
  declare originalTimezone: string
  @column()
  declare proposedEndLocal: string | null
  @column.dateTime()
  declare proposedEndsAt: DateTime | null
  @column()
  declare proposedStartLocal: string | null
  @column.dateTime()
  declare proposedStartsAt: DateTime | null
  @column()
  declare providerNotes: string | null
  @column()
  declare reference: string
  @column.dateTime()
  declare responseExpiresAt: DateTime
  @column()
  declare spaceId: number | null
  @column.dateTime()
  declare startsAt: DateTime
  @column()
  declare status: string
  @column()
  declare statusReason: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare venueId: number
}
