/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type BookingTransformer from '#transformers/booking_transformer'
import type CompanyProfileTransformer from '#transformers/company_profile_transformer'
import type CompanyTransformer from '#transformers/company_transformer'
import type HallTransformer from '#transformers/hall_transformer'
import type NotificationTransformer from '#transformers/notification_transformer'
import type PushInstallationTransformer from '#transformers/push_installation_transformer'
import type ServiceTransformer from '#transformers/service_transformer'
import type UserProfileTransformer from '#transformers/user_profile_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Booking = InferData<BookingTransformer>
  export namespace Booking {
    export type Variants = InferVariants<BookingTransformer>
  }
  export type CompanyProfile = InferData<CompanyProfileTransformer>
  export namespace CompanyProfile {
    export type Variants = InferVariants<CompanyProfileTransformer>
  }
  export type Company = InferData<CompanyTransformer>
  export namespace Company {
    export type Variants = InferVariants<CompanyTransformer>
  }
  export type Hall = InferData<HallTransformer>
  export namespace Hall {
    export type Variants = InferVariants<HallTransformer>
  }
  export type Notification = InferData<NotificationTransformer>
  export namespace Notification {
    export type Variants = InferVariants<NotificationTransformer>
  }
  export type PushInstallation = InferData<PushInstallationTransformer>
  export namespace PushInstallation {
    export type Variants = InferVariants<PushInstallationTransformer>
  }
  export type Service = InferData<ServiceTransformer>
  export namespace Service {
    export type Variants = InferVariants<ServiceTransformer>
  }
  export type UserProfile = InferData<UserProfileTransformer>
  export namespace UserProfile {
    export type Variants = InferVariants<UserProfileTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
